# Generated by Django 4.2 on 2023-05-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="a",
            new_name="Demo_Model",
        ),
    ]
